### ISSUE TITLE
queue.host should accept a hostname as well as an IP

### ISSUE THREAD

**Issue by emberdart** [dadi/queue#10]
https://github.com/dadi/queue/blob/master/config.js#L18

currently restricts use to only IPs but should also allow hostnames.

**Comment by adamkdean** [comment]
This should be possible. `rsmq-worker` doesn't place a restriction on this.

> `options.host: ( String optional; default = "localhost" ) Host to connect to redis if no rsmq or redis instance has been defined`
>
> https://github.com/mpneuried/rsmq-worker
